name: CI
on:
  pull_request:

jobs:
  Validate:
    name: Run action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run type-check
      - run: npm run test